### ISSUE TITLE
Portal Theming

### ISSUE THREAD

**Issue by elcopeland** [InteractiveDesignAndDevelopment/team-planning#1]
Includes: 
- [x] [Portal Theming](https://github.com/InteractiveDesignAndDevelopment/student-portal-theming)
- [x] [Portal Maintenance Page](https://github.com/InteractiveDesignAndDevelopment/portal-maintenance-page)
- [x] [Staff Portal Login Helper](https://github.com/InteractiveDesignAndDevelopment/staff-portal-login-helper)

**Comment by elliemcopeland** [comment]
Includes: 
- [Portal Rethemeing](https://github.com/InteractiveDesignAndDevelopment/student-portal-theming)
- [Portal Maintenance Page](https://github.com/InteractiveDesignAndDevelopment/portal-maintenance-page)

**Comment by elliemcopeland** [comment]
[Issue Board for All](https://github.com/InteractiveDesignAndDevelopment/student-portal-theming/issues#boards?repos=107576494,108544517,107303067)

**Comment by elcopeland** [comment]
Last steps: education for Elizabeth.
