### ISSUE TITLE
web.mercer.edu

### ISSUE THREAD

**Issue by elcopeland** [InteractiveDesignAndDevelopment/team-planning#14]
Make a new site for MU Web. 

[Follow this sitemap](https://docs.google.com/document/d/1uPoI1ap9otLn8rjKEuXtIei456C0z38tms1qQ2-buTk/edit#)

**Comment by elcopeland** [comment]
TBD on if this will need to live under Marketing or as its own entity

**Comment by cinakur** [comment]
Canceling until later date.
