### ISSUE TITLE
IT Org Chart --> Figma

### ISSUE THREAD

**Issue by elcopeland** [InteractiveDesignAndDevelopment/team-planning#8]
[Figma File](https://www.figma.com/file/f26fC1UbVzuQqCI0YlTxX3vT/IT-Org-Chart)

**Comment by elliemcopeland** [comment]
On this page: [Org Chart](http://it.mercer.edu/faculty/about_it-organizational_chart.htm)

**Comment by elcopeland** [comment]
- [x] Create Figma Doodad
- [ ] Complete Org Chart in Figma
- [ ] Embed in IT page

**Comment by elcopeland** [comment]
Deployed on IT Site.

**Comment by elcopeland** [comment]
For V2: remove LC and JS from implied departments, move underneath Kirk
